/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2021, Avonni Labs, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * - Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { LightningElement } from 'lwc';

export default class EmojiPicker extends LightningElement {
    goToSection(event) {
        let section = this.template.querySelector(
            `section[data-value=${event.target.value}]`
        );

        this.template
            .querySelector('.avonni-emoji-viewer')
            .scrollTo({ top: section.offsetTop });
    }

    dispatchSelectEmojiEvent(event) {
        this.dispatchEvent(
            new CustomEvent('emoji', {
                composed: true,
                bubbles: true,
                detail: {
                    value: event.target.value
                }
            })
        );
    }

    categories = [
        {
            title: 'Smileys & People',
            value: 'SmileysPeople',
            iconName: 'utility:smiley_and_people'
        },
        {
            title: 'Animals & Nature',
            value: 'AnimalsNature',
            iconName: 'utility:animal_and_nature'
        },
        {
            title: 'Food & Drink',
            value: 'FoodDrink',
            iconName: 'utility:food_and_drink'
        },
        {
            title: 'Travel & Places',
            value: 'TravelPlaces',
            iconName: 'utility:travel_and_places'
        },
        {
            title: 'Activities',
            value: 'Activities',
            iconName: 'utility:activity'
        },
        { title: 'Objects', value: 'Objects', iconName: 'utility:light_bulb' },
        { title: 'Symbols', value: 'Symbols', iconName: 'utility:symbols' },
        { title: 'Flags', value: 'Flags', iconName: 'utility:priority' }
    ];

    emojiGroups = [
        {
            title: 'Smileys & People',
            value: 'SmileysPeople',
            emojis: [
                { title: 'Grinning face', value: '😀' },
                { title: 'Grinning face with smiling eyes', value: '😁' },
                { title: 'Face with tears of joy', value: '😂' },
                { title: 'Smiling face with open mouth', value: '😃' },
                {
                    title: 'Smiling face with open mouth smiling eyes',
                    value: '😄'
                },
                {
                    title: 'Smiling face with open mouth cold sweat',
                    value: '😅'
                },
                {
                    title: 'Smiling face with open mouth closed eyes',
                    value: '😆'
                },
                { title: 'Winking face', value: '😉' },
                { title: 'Smiling face with smiling eyes', value: '😊' },
                { title: 'Face savoring delicious food', value: '😋' },
                { title: 'Smiling face with sunglasses', value: '😎' },
                { title: 'Smiling face with heart eyes', value: '😍' },
                { title: 'Face blowing a kiss', value: '😘' },
                { title: 'Kissing face', value: '😗' },
                { title: 'Kissing face with smiling eyes', value: '😙' },
                { title: 'Kissing face with closed eyes', value: '😚' },
                { title: 'Slightly smiling face', value: '🙂' },
                { title: 'Neutral face', value: '😐' },
                { title: 'Expressionless face', value: '😑' },
                { title: 'Face without mouth', value: '😶' },
                { title: 'Smirking face', value: '😏' },
                { title: 'Persevering face', value: '😣' },
                { title: 'Disappointed but relieved face', value: '😥' },
                { title: 'Face with open mouth', value: '😮' },
                { title: 'Hushed face', value: '😯' },
                { title: 'Sleepy face', value: '😪' },
                { title: 'Tired face', value: '😫' },
                { title: 'Sleeping face', value: '😴' },
                { title: 'Relieved face', value: '😌' },
                { title: 'Face with stuck out tongue', value: '😛' },
                {
                    title: 'Face with stuck out tongue winking eye',
                    value: '😜'
                },
                {
                    title: 'Face with stuck out tongue closed eyes',
                    value: '😝'
                },
                { title: 'Unamused face', value: '😒' },
                { title: 'Face with cold sweat', value: '😓' },
                { title: 'Pensive face', value: '😔' },
                { title: 'Confused face', value: '😕' },
                { title: 'Astonished face', value: '😲' },
                { title: 'Confounded face', value: '😖' },
                { title: 'Disappointed face', value: '😞' },
                { title: 'Worried face', value: '😟' },
                { title: 'Face with steam from nose', value: '😤' },
                { title: 'Crying face', value: '😢' },
                { title: 'Loudly crying face', value: '😭' },
                { title: 'Frowning face with open mouth', value: '😦' },
                { title: 'Anguished face', value: '😧' },
                { title: 'Fearful face', value: '😨' },
                { title: 'Weary face', value: '😩' },
                { title: 'Grimacing face', value: '😬' },
                { title: 'Face with open mouth cold sweat', value: '😰' },
                { title: 'Face screaming in fear', value: '😱' },
                { title: 'Flushed face', value: '😳' },
                { title: 'Dizzy face', value: '😵' },
                { title: 'Pouting face', value: '😡' },
                { title: 'Angry face', value: '😠' },
                { title: 'Smiling face with halo', value: '😇' },
                { title: 'Face with medical mask', value: '😷' },
                { title: 'Smiling face with horns', value: '😈' },
                { title: 'Angry face with horns', value: '👿' },
                { title: 'Ogre', value: '👹' },
                { title: 'Goblin', value: '👺' },
                { title: 'Skull', value: '💀' },
                { title: 'Ghost', value: '👻' },
                { title: 'Alien', value: '👽' },
                { title: 'Alien monster', value: '👾' },
                { title: 'Pile of poo', value: '💩' },
                { title: 'Smiling cat face with open mouth', value: '😺' },
                { title: 'Grinning cat face with smiling eyes', value: '😸' },
                { title: 'Cat face with tears of joy', value: '😹' },
                { title: 'Smiling cat face with heart eyes', value: '😻' },
                { title: 'Cat face with wry smile', value: '😼' },
                { title: 'Kissing cat face with closed eyes', value: '😽' },
                { title: 'Weary cat face', value: '🙀' },
                { title: 'Crying cat face', value: '😿' },
                { title: 'Pouting cat face', value: '😾' },
                { title: 'See no evil monkey', value: '🙈' },
                { title: 'Hear no evil monkey', value: '🙉' },
                { title: 'Speak no evil monkey', value: '🙊' },
                { title: 'Boy', value: '👦' },
                { title: 'Girl', value: '👧' },
                { title: 'Man', value: '👨' },
                { title: 'Woman', value: '👩' },
                { title: 'Old man', value: '👴' },
                { title: 'Old woman', value: '👵' },
                { title: 'Baby', value: '👶' },
                { title: 'Baby angel', value: '👼' },
                { title: 'Police officer', value: '👮' },
                { title: 'Guard', value: '💂' },
                { title: 'Construction worker', value: '👷' },
                { title: 'Person wearing turban', value: '👳' },
                { title: 'Blond haired person', value: '👱' },
                { title: 'Santa claus', value: '🎅' },
                { title: 'Princess', value: '👸' },
                { title: 'Bride with veil', value: '👰' },
                { title: 'Man with Chinese cap', value: '👲' },
                { title: 'Person frowning', value: '🙍' },
                { title: 'Person pouting', value: '🙎' },
                { title: 'Person gesturing no', value: '🙅' },
                { title: 'Person gesturing ok', value: '🙆' },
                { title: 'Person tipping hand', value: '💁' },
                { title: 'Person raising hand', value: '🙋' },
                { title: 'Person bowing', value: '🙇' },
                { title: 'Person getting massage', value: '💆' },
                { title: 'Person getting haircut', value: '💇' },
                { title: 'Person walking', value: '🚶' },
                { title: 'Person running', value: '🏃' },
                { title: 'Woman dancing', value: '💃' },
                { title: 'People with bunny ears partying', value: '👯' },
                { title: 'Bust in silhouette', value: '👤' },
                { title: 'Busts in silhouette', value: '👥' },
                { title: 'Horse racing', value: '🏇' },
                { title: 'Snowboarder', value: '🏂' },
                { title: 'Person surfing', value: '🏄' },
                { title: 'Person rowing boat', value: '🚣' },
                { title: 'Person swimming', value: '🏊' },
                { title: 'Person biking', value: '🚴' },
                { title: 'Person mountain biking', value: '🚵' },
                { title: 'Man and woman holding hands', value: '👫' },
                { title: 'Two men holding hands', value: '👬' },
                { title: 'Two women holding hands', value: '👭' },
                { title: 'Kiss', value: '💏' },
                { title: 'Couple with heart', value: '💑' },
                { title: 'Family', value: '👪' },
                { title: 'Flexed biceps', value: '💪' },
                { title: 'Backhand index pointing left', value: '👈' },
                { title: 'Backhand index pointing right', value: '👉' },
                { title: 'Index pointing up', value: '☝️' },
                { title: 'Backhand index pointing up', value: '👆' },
                { title: 'Backhand index pointing down', value: '👇' },
                { title: 'Victory hand', value: '✌️' },
                { title: 'Raised hand', value: '✋' },
                { title: 'Ok hand', value: '👌' },
                { title: 'Thumbs up', value: '👍' },
                { title: 'Thumbs down', value: '👎' },
                { title: 'Raised fist', value: '✊' },
                { title: 'Oncoming fist', value: '👊' },
                { title: 'Waving hand', value: '👋' },
                { title: 'Clapping hands', value: '👏' },
                { title: 'Open hands', value: '👐' },
                { title: 'Raising hands', value: '🙌' },
                { title: 'Folded hands', value: '🙏' },
                { title: 'Nail polish', value: '💅' },
                { title: 'Ear', value: '👂' },
                { title: 'Nose', value: '👃' },
                { title: 'Footprints', value: '👣' },
                { title: 'Eyes', value: '👀' },
                { title: 'Tongue', value: '👅' },
                { title: 'Mouth', value: '👄' },
                { title: 'Kiss mark', value: '💋' },
                { title: 'Heart with arrow', value: '💘' },
                { title: 'Red heart', value: '❤️' },
                { title: 'Beating heart', value: '💓' },
                { title: 'Broken heart', value: '💔' },
                { title: 'Two hearts', value: '💕' },
                { title: 'Sparkling heart', value: '💖' },
                { title: 'Growing heart', value: '💗' },
                { title: 'Blue heart', value: '💙' },
                { title: 'Green heart', value: '💚' },
                { title: 'Yellow heart', value: '💛' },
                { title: 'Purple heart', value: '💜' },
                { title: 'Heart with ribbon', value: '💝' },
                { title: 'Revolving hearts', value: '💞' },
                { title: 'Heart decoration', value: '💟' },
                { title: 'Love letter', value: '💌' },
                { title: 'Zzz', value: '💤' },
                { title: 'Anger symbol', value: '💢' },
                { title: 'Bomb', value: '💣' },
                { title: 'Collision', value: '💥' },
                { title: 'Sweat droplets', value: '💦' },
                { title: 'Dashing away', value: '💨' },
                { title: 'Dizzy', value: '💫' },
                { title: 'Speech balloon', value: '💬' },
                { title: 'Thought balloon', value: '💭' },
                { title: 'Glasses', value: '👓' },
                { title: 'Necktie', value: '👔' },
                { title: 'Tee-shirt', value: '👕' },
                { title: 'Jeans', value: '👖' },
                { title: 'Dress', value: '👗' },
                { title: 'Kimono', value: '👘' },
                { title: 'Bikini', value: '👙' },
                { title: "Woman's clothes", value: '👚' },
                { title: 'Purse', value: '👛' },
                { title: 'Handbag', value: '👜' },
                { title: 'Clutch bag', value: '👝' },
                { title: 'School backpack', value: '🎒' },
                { title: "Man's shoe", value: '👞' },
                { title: 'Running shoe', value: '👟' },
                { title: 'High-heeled shoe', value: '👠' },
                { title: "Woman's sandal", value: '👡' },
                { title: "Woman's boot", value: '👢' },
                { title: 'Crown', value: '👑' },
                { title: "Woman's hat", value: '👒' },
                { title: 'Top hat', value: '🎩' },
                { title: 'Graduation cap', value: '🎓' },
                { title: 'Lipstick', value: '💄' },
                { title: 'Ring', value: '💍' },
                { title: 'Gemstone', value: '💎' }
            ]
        },
        {
            title: 'Animals & Nature',
            value: 'AnimalsNature',
            emojis: [
                { title: 'Monkey face', value: '🐵' },
                { title: 'Monkey', value: '🐒' },
                { title: 'Dog face', value: '🐶' },
                { title: 'Dog', value: '🐕' },
                { title: 'Poodle', value: '🐩' },
                { title: 'Wolf face', value: '🐺' },
                { title: 'Cat face', value: '🐱' },
                { title: 'Cat', value: '🐈' },
                { title: 'Tiger face', value: '🐯' },
                { title: 'Tiger', value: '🐅' },
                { title: 'Leopard', value: '🐆' },
                { title: 'Horse face', value: '🐴' },
                { title: 'Horse', value: '🐎' },
                { title: 'Cow face', value: '🐮' },
                { title: 'Ox', value: '🐂' },
                { title: 'Water buffalo', value: '🐃' },
                { title: 'Cow', value: '🐄' },
                { title: 'Pig face', value: '🐷' },
                { title: 'Pig', value: '🐖' },
                { title: 'Boar', value: '🐗' },
                { title: 'Pig nose', value: '🐽' },
                { title: 'Ram', value: '🐏' },
                { title: 'Sheep', value: '🐑' },
                { title: 'Goat', value: '🐐' },
                { title: 'Camel', value: '🐪' },
                { title: 'Two-hump camel', value: '🐫' },
                { title: 'Elephant', value: '🐘' },
                { title: 'Mouse face', value: '🐭' },
                { title: 'Mouse', value: '🐁' },
                { title: 'Rat', value: '🐀' },
                { title: 'Hamster face', value: '🐹' },
                { title: 'Rabbit face', value: '🐰' },
                { title: 'Rabbit', value: '🐇' },
                { title: 'Bear face', value: '🐻' },
                { title: 'Koala', value: '🐨' },
                { title: 'Panda face', value: '🐼' },
                { title: 'Paw prints', value: '🐾' },
                { title: 'Chicken', value: '🐔' },
                { title: 'Rooster', value: '🐓' },
                { title: 'Hatching chick', value: '🐣' },
                { title: 'Baby chick', value: '🐤' },
                { title: 'Front-facing baby chick', value: '🐥' },
                { title: 'Bird', value: '🐦' },
                { title: 'Penguin', value: '🐧' },
                { title: 'Frog face', value: '🐸' },
                { title: 'Crocodile', value: '🐊' },
                { title: 'Turtle', value: '🐢' },
                { title: 'Snake', value: '🐍' },
                { title: 'Dragon face', value: '🐲' },
                { title: 'Dragon', value: '🐉' },
                { title: 'Spouting whale', value: '🐳' },
                { title: 'Whale', value: '🐋' },
                { title: 'Dolphin', value: '🐬' },
                { title: 'Fish', value: '🐟' },
                { title: 'Tropical fish', value: '🐠' },
                { title: 'Blowfish', value: '🐡' },
                { title: 'Octopus', value: '🐙' },
                { title: 'Spiral shell', value: '🐚' },
                { title: 'Snail', value: '🐌' },
                { title: 'Bug', value: '🐛' },
                { title: 'Ant', value: '🐜' },
                { title: 'Honeybee', value: '🐝' },
                { title: 'Lady beetle', value: '🐞' },
                { title: 'Bouquet', value: '💐' },
                { title: 'Cherry blossom', value: '🌸' },
                { title: 'White flower', value: '💮' },
                { title: 'Rose', value: '🌹' },
                { title: 'Hibiscus', value: '🌺' },
                { title: 'Sunflower', value: '🌻' },
                { title: 'Blossom', value: '🌼' },
                { title: 'Tulip', value: '🌷' },
                { title: 'Seedling', value: '🌱' },
                { title: 'Evergreen tree', value: '🌲' },
                { title: 'Deciduous tree', value: '🌳' },
                { title: 'Palm tree', value: '🌴' },
                { title: 'Cactus', value: '🌵' },
                { title: 'Sheaf of rice', value: '🌾' },
                { title: 'Herb', value: '🌿' },
                { title: 'Four-leaf clover', value: '🍀' },
                { title: 'Maple leaf', value: '🍁' },
                { title: 'Fallen leaf', value: '🍂' },
                { title: 'Leaf fluttering in wind', value: '🍃' }
            ]
        },
        {
            title: 'Food & Drink',
            value: 'FoodDrink',
            emojis: [
                { title: 'Grapes', value: '🍇' },
                { title: 'Melon', value: '🍈' },
                { title: 'Watermelon', value: '🍉' },
                { title: 'Tangerine', value: '🍊' },
                { title: 'Lemon', value: '🍋' },
                { title: 'Banana', value: '🍌' },
                { title: 'Pineapple', value: '🍍' },
                { title: 'Red apple', value: '🍎' },
                { title: 'Green apple', value: '🍏' },
                { title: 'Pear', value: '🍐' },
                { title: 'Peach', value: '🍑' },
                { title: 'Cherries', value: '🍒' },
                { title: 'Strawberry', value: '🍓' },
                { title: 'Tomato', value: '🍅' },
                { title: 'Eggplant', value: '🍆' },
                { title: 'Ear of corn', value: '🌽' },
                { title: 'Mushroom', value: '🍄' },
                { title: 'Chestnut', value: '🌰' },
                { title: 'Bread', value: '🍞' },
                { title: 'Meat on bone', value: '🍖' },
                { title: 'Poultry leg', value: '🍗' },
                { title: 'Hamburger', value: '🍔' },
                { title: 'French fries', value: '🍟' },
                { title: 'Pizza', value: '🍕' },
                { title: 'Cooking', value: '🍳' },
                { title: 'Pot of food', value: '🍲' },
                { title: 'Bento box', value: '🍱' },
                { title: 'Rice cracker', value: '🍘' },
                { title: 'Rice ball', value: '🍙' },
                { title: 'Cooked rice', value: '🍚' },
                { title: 'Curry rice', value: '🍛' },
                { title: 'Steaming bowl', value: '🍜' },
                { title: 'Spaghetti', value: '🍝' },
                { title: 'Roasted sweet potato', value: '🍠' },
                { title: 'Oden', value: '🍢' },
                { title: 'Sushi', value: '🍣' },
                { title: 'Fried shrimp', value: '🍤' },
                { title: 'Fish cake with swirl', value: '🍥' },
                { title: 'Dango', value: '🍡' },
                { title: 'Soft ice cream', value: '🍦' },
                { title: 'Shaved ice', value: '🍧' },
                { title: 'Ice cream', value: '🍨' },
                { title: 'Doughnut', value: '🍩' },
                { title: 'Cookie', value: '🍪' },
                { title: 'Birthday cake', value: '🎂' },
                { title: 'Shortcake', value: '🍰' },
                { title: 'Chocolate bar', value: '🍫' },
                { title: 'Candy', value: '🍬' },
                { title: 'Lollipop', value: '🍭' },
                { title: 'Custard', value: '🍮' },
                { title: 'Honey pot', value: '🍯' },
                { title: 'Baby bottle', value: '🍼' },
                { title: 'Hot beverage', value: '☕️' },
                { title: 'Teacup without handle', value: '🍵' },
                { title: 'Sake', value: '🍶' },
                { title: 'Wine glass', value: '🍷' },
                { title: 'Cocktail glass', value: '🍸' },
                { title: 'Tropical drink', value: '🍹' },
                { title: 'Beer mug', value: '🍺' },
                { title: 'Clinking beer mugs', value: '🍻' },
                { title: 'Fork and knife', value: '🍴' },
                { title: 'Kitchen knife', value: '🔪' }
            ]
        },
        {
            title: 'Travel & Places',
            value: 'TravelPlaces',
            emojis: [
                { title: 'Globe showing Europe Africa', value: '🌍' },
                { title: 'Globe showing Americas', value: '🌎' },
                { title: 'Globe showing Asia Australia', value: '🌏' },
                { title: 'Globe with meridians', value: '🌐' },
                { title: 'Map of Japan', value: '🗾' },
                { title: 'Volcano', value: '🌋' },
                { title: 'Mount Fuji', value: '🗻' },
                { title: 'House', value: '🏠' },
                { title: 'House with garden', value: '🏡' },
                { title: 'Office building', value: '🏢' },
                { title: 'Japanese post office', value: '🏣' },
                { title: 'Post office', value: '🏤' },
                { title: 'Hospital', value: '🏥' },
                { title: 'Bank', value: '🏦' },
                { title: 'Hotel', value: '🏨' },
                { title: 'Love hotel', value: '🏩' },
                { title: 'Convenience store', value: '🏪' },
                { title: 'School', value: '🏫' },
                { title: 'Department store', value: '🏬' },
                { title: 'Factory', value: '🏭' },
                { title: 'Japanese castle', value: '🏯' },
                { title: 'Castle', value: '🏰' },
                { title: 'Wedding', value: '💒' },
                { title: 'Tokyo tower', value: '🗼' },
                { title: 'Statue of Liberty', value: '🗽' },
                { title: 'Church', value: '⛪' },
                { title: 'Fountain', value: '⛲' },
                { title: 'Tent', value: '⛺' },
                { title: 'Foggy', value: '🌁' },
                { title: 'Night with stars', value: '🌃' },
                { title: 'Sunrise over mountains', value: '🌄' },
                { title: 'Sunrise', value: '🌅' },
                { title: 'Cityscape at dusk', value: '🌆' },
                { title: 'Sunset', value: '🌇' },
                { title: 'Bridge at night', value: '🌉' },
                { title: 'Hot springs', value: '♨️' },
                { title: 'Milky Way', value: '🌌' },
                { title: 'Carousel horse', value: '🎠' },
                { title: 'Ferris wheel', value: '🎡' },
                { title: 'Roller coaster', value: '🎢' },
                { title: 'Barber pole', value: '💈' },
                { title: 'Circus tent', value: '🎪' },
                { title: 'Performing arts', value: '🎭' },
                { title: 'Artist palette', value: '🎨' },
                { title: 'Slot machine', value: '🎰' },
                { title: 'Locomotive', value: '🚂' },
                { title: 'Railway car', value: '🚃' },
                { title: 'High-speed train', value: '🚄' },
                { title: 'High speed train with bullet nose', value: '🚅' },
                { title: 'Train', value: '🚆' },
                { title: 'Metro', value: '🚇' },
                { title: 'Light rail', value: '🚈' },
                { title: 'Station', value: '🚉' },
                { title: 'Tram', value: '🚊' },
                { title: 'Monorail', value: '🚝' },
                { title: 'Mountain railway', value: '🚞' },
                { title: 'Tram car', value: '🚋' },
                { title: 'Bus', value: '🚌' },
                { title: 'Oncoming bus', value: '🚍' },
                { title: 'Trolleybus', value: '🚎' },
                { title: 'Minibus', value: '🚐' },
                { title: 'Ambulance', value: '🚑' },
                { title: 'Fire engine', value: '🚒' },
                { title: 'Police car', value: '🚓' },
                { title: 'Oncoming police car', value: '🚔' },
                { title: 'Taxi', value: '🚕' },
                { title: 'Oncoming taxi', value: '🚖' },
                { title: 'Automobile', value: '🚗' },
                { title: 'Oncoming automobile', value: '🚘' },
                { title: 'Sport utility vehicle', value: '🚙' },
                { title: 'Delivery truck', value: '🚚' },
                { title: 'Articulated lorry', value: '🚛' },
                { title: 'Tractor', value: '🚜' },
                { title: 'Bicycle', value: '🚲' },
                { title: 'Bus stop', value: '🚏' },
                { title: 'Fuel pump', value: '⛽' },
                { title: 'Police car light', value: '🚨' },
                { title: 'Horizontal traffic light', value: '🚥' },
                { title: 'Vertical traffic light', value: '🚦' },
                { title: 'Construction', value: '🚧' },
                { title: 'Anchor', value: '⚓️' },
                { title: 'Sailboat', value: '⛵' },
                { title: 'Speedboat', value: '🚤' },
                { title: 'Ship', value: '🚢' },
                { title: 'Airplane', value: '✈️' },
                { title: 'Seat', value: '💺' },
                { title: 'Helicopter', value: '🚁' },
                { title: 'Suspension railway', value: '🚟' },
                { title: 'Mountain cableway', value: '🚠' },
                { title: 'Aerial tramway', value: '🚡' },
                { title: 'Rocket', value: '🚀' },
                { title: 'Door', value: '🚪' },
                { title: 'Toilet', value: '🚽' },
                { title: 'Shower', value: '🚿' },
                { title: 'Person taking bath', value: '🛀' },
                { title: 'Bathtub', value: '🛁' },
                { title: 'Hourglass', value: '⌛️' },
                { title: 'Hourglass with flowing sand', value: '⏳' },
                { title: 'Watch', value: '⌚️' },
                { title: 'Alarm clock', value: '⏰' },
                { title: "Twelve o'clock", value: '🕛' },
                { title: 'Twelve thirty', value: '🕧' },
                { title: "One o'clock", value: '🕐' },
                { title: 'One thirty', value: '🕜' },
                { title: "Two'o'clock", value: '🕑' },
                { title: "Two'thirty", value: '🕝' },
                { title: "Three o'clock", value: '🕒' },
                { title: 'Three thirty', value: '🕞' },
                { title: "Four o'clock", value: '🕓' },
                { title: 'Four thirty', value: '🕟' },
                { title: "Five o'clock", value: '🕔' },
                { title: 'Five thirty', value: '🕠' },
                { title: "Six o'clock", value: '🕕' },
                { title: 'Six thirty', value: '🕡' },
                { title: "Seven o'clock", value: '🕖' },
                { title: 'Seven thirty', value: '🕢' },
                { title: "Eight o'clock", value: '🕗' },
                { title: 'Eight thirty', value: '🕣' },
                { title: "Nine o'clock", value: '🕘' },
                { title: 'Nine thirty', value: '🕤' },
                { title: "Ten o'clock", value: '🕙' },
                { title: 'Ten thirty', value: '🕥' },
                { title: "Eleven o'clock", value: '🕚' },
                { title: 'Eleven thirty', value: '🕦' },
                { title: 'New moon', value: '🌑' },
                { title: 'Waxing crescent moon', value: '🌒' },
                { title: 'First quarter moon', value: '🌓' },
                { title: 'Waxing gibbous moon', value: '🌔' },
                { title: 'Full moon', value: '🌕' },
                { title: 'Waning gibbous moon', value: '🌖' },
                { title: 'Last quarter moon', value: '🌗' },
                { title: 'Waning crescent moon', value: '🌘' },
                { title: 'Crescent moon', value: '🌙' },
                { title: 'New moon face', value: '🌚' },
                { title: 'First quarter moon with face', value: '🌛' },
                { title: 'Last quarter moon with face', value: '🌜' },
                { title: 'Sun', value: '☀️' },
                { title: 'Full moon with face', value: '🌝' },
                { title: 'Sun with face', value: '🌞' },
                { title: 'White medium star', value: '⭐️' },
                { title: 'Glowing star', value: '🌟' },
                { title: 'Shooting star', value: '🌠' },
                { title: 'Cloud', value: '☁️' },
                { title: 'Sun behind cloud', value: '⛅' },
                { title: 'Cyclone', value: '🌀' },
                { title: 'Rainbow', value: '🌈' },
                { title: 'Closed umbrella', value: '🌂' },
                { title: 'Umbrella with rain drops', value: '☔️' },
                { title: 'High voltage', value: '⚡️' },
                { title: 'Snowflake', value: '❄️' },
                { title: 'Snowman without snow', value: '⛄' },
                { title: 'Fire', value: '🔥' },
                { title: 'Droplet', value: '💧' },
                { title: 'Water wave', value: '🌊' }
            ]
        },
        {
            title: 'Activities',
            value: 'Activities',
            emojis: [
                { title: 'Jack-o-lantern', value: '🎃' },
                { title: 'Christmas tree', value: '🎄' },
                { title: 'Fireworks', value: '🎆' },
                { title: 'Sparkler', value: '🎇' },
                { title: 'Sparkles', value: '✨' },
                { title: 'Balloon', value: '🎈' },
                { title: 'Party popper', value: '🎉' },
                { title: 'Confetti ball', value: '🎊' },
                { title: 'Tanabata tree', value: '🎋' },
                { title: 'Pine decoration', value: '🎍' },
                { title: 'Japanese dolls', value: '🎎' },
                { title: 'Carp streamer', value: '🎏' },
                { title: 'Wind chime', value: '🎐' },
                { title: 'Moon-viewing ceremony', value: '🎑' },
                { title: 'Ribbon', value: '🎀' },
                { title: 'Wrapped gift', value: '🎁' },
                { title: 'Ticket', value: '🎫' },
                { title: 'Trophy', value: '🏆' },
                { title: 'Soccer ball', value: '⚽' },
                { title: 'Baseball', value: '⚾️' },
                { title: 'Basketball', value: '🏀' },
                { title: 'American football', value: '🏈' },
                { title: 'Rugby football', value: '🏉' },
                { title: 'Tennis', value: '🎾' },
                { title: 'Pool 8-ball', value: '🎱' },
                { title: 'Bowling', value: '🎳' },
                { title: 'Direct hit', value: '🎯' },
                { title: 'Flag in hole', value: '⛳' },
                { title: 'Fishing pole', value: '🎣' },
                { title: 'Running shirt', value: '🎽' },
                { title: 'Skis', value: '🎿' },
                { title: 'Video game', value: '🎮' },
                { title: 'Game die', value: '🎲' },
                { title: 'Spade suit', value: '♠️' },
                { title: 'Heart suit', value: '♥️' },
                { title: 'Diamond suit', value: '♦️' },
                { title: 'Club suit', value: '♣️' },
                { title: 'Joker', value: '🃏' },
                { title: 'Mahjong red dragon', value: '🀄' },
                { title: 'Flower playing cards', value: '🎴' }
            ]
        },
        {
            title: 'Objects',
            value: 'Objects',
            emojis: [
                { title: 'Muted speaker', value: '🔇' },
                { title: 'Speaker low volume', value: '🔈' },
                { title: 'Speaker medium volume', value: '🔉' },
                { title: 'Speaker high volume', value: '🔊' },
                { title: 'Loudspeaker', value: '📢' },
                { title: 'Megaphone', value: '📣' },
                { title: 'Postal horn', value: '📯' },
                { title: 'Bell', value: '🔔' },
                { title: 'Bell with slash', value: '🔕' },
                { title: 'Musical score', value: '🎼' },
                { title: 'Musical note', value: '🎵' },
                { title: 'Musical notes', value: '🎶' },
                { title: 'Microphone', value: '🎤' },
                { title: 'Headphone', value: '🎧' },
                { title: 'Radio', value: '📻' },
                { title: 'Saxophone', value: '🎷' },
                { title: 'Guitar', value: '🎸' },
                { title: 'Musical keyboard', value: '🎹' },
                { title: 'Trumpet', value: '🎺' },
                { title: 'Violin', value: '🎻' },
                { title: 'Mobile phone', value: '📱' },
                { title: 'Mobile phone with arrow', value: '📲' },
                { title: 'Telephone', value: '☎' },
                { title: 'Telephone receiver', value: '📞' },
                { title: 'Pager', value: '📟' },
                { title: 'Fax machine', value: '📠' },
                { title: 'Battery', value: '🔋' },
                { title: 'Electric plug', value: '🔌' },
                { title: 'Laptop computer', value: '💻' },
                { title: 'Computer disk', value: '💽' },
                { title: 'Floppy disk', value: '💾' },
                { title: 'Optical disk', value: '💿' },
                { title: 'Dvd', value: '📀' },
                { title: 'Movie camera', value: '🎥' },
                { title: 'Clapper board', value: '🎬' },
                { title: 'Television', value: '📺' },
                { title: 'Camera', value: '📷' },
                { title: 'Video camera', value: '📹' },
                { title: 'Videocassette', value: '📼' },
                { title: 'Left-pointing magnifying glass', value: '🔍' },
                { title: 'Right-pointing magnifying glass', value: '🔎' },
                { title: 'Microscope', value: '🔬' },
                { title: 'Telescope', value: '🔭' },
                { title: 'Satellite antenna', value: '📡' },
                { title: 'Light bulb', value: '💡' },
                { title: 'Flashlight', value: '🔦' },
                { title: 'Red paper lantern', value: '🏮' },
                { title: 'Notebook with decorative cover', value: '📔' },
                { title: 'Closed book', value: '📕' },
                { title: 'Open book', value: '📖' },
                { title: 'Green book', value: '📗' },
                { title: 'Blue book', value: '📘' },
                { title: 'Orange book', value: '📙' },
                { title: 'Books', value: '📚' },
                { title: 'Notebook', value: '📓' },
                { title: 'Ledger', value: '📒' },
                { title: 'Page with curl', value: '📃' },
                { title: 'Scroll', value: '📜' },
                { title: 'Page facing up', value: '📄' },
                { title: 'Newspaper', value: '📰' },
                { title: 'Bookmark tabs', value: '📑' },
                { title: 'Bookmark', value: '🔖' },
                { title: 'Money bag', value: '💰' },
                { title: 'Yen banknote', value: '💴' },
                { title: 'Dollar banknote', value: '💵' },
                { title: 'Euro banknote', value: '💶' },
                { title: 'Pound banknote', value: '💷' },
                { title: 'Money with wings', value: '💸' },
                { title: 'Credit card', value: '💳' },
                { title: 'Chart increasing with yen', value: '💹' },
                { title: 'Currency exchange', value: '💱' },
                { title: 'Heavy dollar sign', value: '💲' },
                { title: 'Envelope', value: '✉️' },
                { title: 'Email', value: '📧' },
                { title: 'Incoming envelope', value: '📨' },
                { title: 'Envelope with arrow', value: '📩' },
                { title: 'Outbox tray', value: '📤' },
                { title: 'Inbox tray', value: '📥' },
                { title: 'Package', value: '📦' },
                { title: 'Closed mailbox with raised flag', value: '📫' },
                { title: 'Closed mailbox with lowered flag', value: '📪' },
                { title: 'Open mailbox with raised flag', value: '📬' },
                { title: 'Open mailbox with lowered flag', value: '📭' },
                { title: 'Postbox', value: '📮' },
                { title: 'Pencil', value: '✏️' },
                { title: 'Black nib', value: '✒️' },
                { title: 'Memo', value: '📝' },
                { title: 'Briefcase', value: '💼' },
                { title: 'File folder', value: '📁' },
                { title: 'Open file folder', value: '📂' },
                { title: 'Calendar', value: '📅' },
                { title: 'Tear-off calendar', value: '📆' },
                { title: 'Card index', value: '📇' },
                { title: 'Chart increasing', value: '📈' },
                { title: 'Chart decreasing', value: '📉' },
                { title: 'Bar chart', value: '📊' },
                { title: 'Clipboard', value: '📋' },
                { title: 'Pushpin', value: '📌' },
                { title: 'Round pushpin', value: '📍' },
                { title: 'Paperclip', value: '📎' },
                { title: 'Straight ruler', value: '📏' },
                { title: 'Triangular ruler', value: '📐' },
                { title: 'Scissors', value: '✂️' },
                { title: 'Locked', value: '🔒' },
                { title: 'Unlocked', value: '🔓' },
                { title: 'Locked with pen', value: '🔏' },
                { title: 'Locked with key', value: '🔐' },
                { title: 'Key', value: '🔑' },
                { title: 'Hammer', value: '🔨' },
                { title: 'Pistol', value: '🔫' },
                { title: 'Wrench', value: '🔧' },
                { title: 'Nut and bolt', value: '🔩' },
                { title: 'Link', value: '🔗' },
                { title: 'Syringe', value: '💉' },
                { title: 'Pill', value: '💊' },
                { title: 'Cigarette', value: '🚬' },
                { title: 'Moai', value: '🗿' },
                { title: 'Crystal ball', value: '🔮' }
            ]
        },
        {
            title: 'Symbols',
            value: 'Symbols',
            emojis: [
                { title: 'ATM sign', value: '🏧' },
                { title: 'Litter in bin sign', value: '🚮' },
                { title: 'Potable water', value: '🚰' },
                { title: 'Wheelchair symbol', value: '♿️' },
                { title: "Men's room", value: '🚹' },
                { title: "Women's room", value: '🚺' },
                { title: 'Restroom', value: '🚻' },
                { title: 'Baby symbol', value: '🚼' },
                { title: 'Water closet', value: '🚾' },
                { title: 'Passport control', value: '🛂' },
                { title: 'Customs', value: '🛃' },
                { title: 'Baggage claim', value: '🛄' },
                { title: 'Left luggage', value: '🛅' },
                { title: 'Warning', value: '⚠️' },
                { title: 'Children crossing', value: '🚸' },
                { title: 'No entry', value: '⛔' },
                { title: 'Prohibited', value: '🚫' },
                { title: 'No bicycles', value: '🚳' },
                { title: 'No smoking', value: '🚭' },
                { title: 'No littering', value: '🚯' },
                { title: 'Non-potable water', value: '🚱' },
                { title: 'No pedestrians', value: '🚷' },
                { title: 'No mobile phones', value: '📵' },
                { title: 'No one under eighteen', value: '🔞' },
                { title: 'Up arrow', value: '⬆️' },
                { title: 'Up right arrow', value: '↗️' },
                { title: 'Right arrow', value: '➡️' },
                { title: 'Down right arrow', value: '↘️' },
                { title: 'Down arrow', value: '⬇️' },
                { title: 'Down left arrow', value: '↙️' },
                { title: 'Left arrow', value: '⬅️' },
                { title: 'Up left arrow', value: '↖️' },
                { title: 'Up down arrow', value: '↕️' },
                { title: 'Left right arrow', value: '↔️' },
                { title: 'Right arrow curving left', value: '↩️' },
                { title: 'Left arrow curving right', value: '↪️' },
                { title: 'Right arrow curving up', value: '⤴️' },
                { title: 'Right arrow curving down', value: '⤵️' },
                { title: 'Clockwise vertical arrows', value: '🔃' },
                { title: 'Anticlockwise arrows button', value: '🔄' },
                { title: 'Back arrow', value: '🔙' },
                { title: 'End arrow', value: '🔚' },
                { title: 'On arrow', value: '🔛' },
                { title: 'Soon arrow', value: '🔜' },
                { title: 'Top arrow', value: '🔝' },
                { title: 'Dotted six-pointed star', value: '🔯' },
                { title: 'Aries', value: '♈' },
                { title: 'Taurus', value: '♉' },
                { title: 'Gemini', value: '♊' },
                { title: 'Cancer', value: '♋' },
                { title: 'Leo', value: '♌' },
                { title: 'Virgo', value: '♍' },
                { title: 'Libra', value: '♎' },
                { title: 'Scorpio', value: '♏' },
                { title: 'Sagittarius', value: '♐' },
                { title: 'Capricorn', value: '♑' },
                { title: 'Aquarius', value: '♒' },
                { title: 'Pisces', value: '♓' },
                { title: 'Ophiuchus', value: '⛎' },
                { title: 'Shuffle tracks button', value: '🔀' },
                { title: 'Repeat button', value: '🔁' },
                { title: 'Repeat single button', value: '🔂' },
                { title: 'Play button', value: '▶️' },
                { title: 'Fast-forward button', value: '⏩' },
                { title: 'Reverse button', value: '◀️' },
                { title: 'Fast-reverse button', value: '⏪' },
                { title: 'Up button', value: '🔼' },
                { title: 'Fast-up button', value: '⏫' },
                { title: 'Down button', value: '🔽' },
                { title: 'Fast-down button', value: '⏬' },
                { title: 'Cinema', value: '🎦' },
                { title: 'Dim button', value: '🔅' },
                { title: 'Bright button', value: '🔆' },
                { title: 'Antenna bars', value: '📶' },
                { title: 'Vibration mode', value: '📳' },
                { title: 'Mobile phone off', value: '📴' },
                { title: 'Recycling symbol', value: '♻️' },
                { title: 'Name badge', value: '📛' },
                { title: 'Japanese symbol for beginner', value: '🔰' },
                { title: 'Trident emblem', value: '🔱' },
                { title: 'Heavy large circle', value: '⭕️' },
                { title: 'White heavy check mark', value: '✅️' },
                { title: 'Ballot box with check', value: '☑️' },
                { title: 'Heavy check mark', value: '✔️' },
                { title: 'Heavy multiplication x', value: '✖️' },
                { title: 'Cross mark', value: '❌️' },
                { title: 'Cross mark button', value: '❎️' },
                { title: 'Heavy plus sign', value: '➕️' },
                { title: 'Heavy minus sign', value: '➖️' },
                { title: 'Heavy division sign', value: '➗️' },
                { title: 'Curly loop', value: '➰️' },
                { title: 'Double curly loop', value: '➿️' },
                { title: 'Part alternation mark', value: '〽️' },
                { title: 'Eight-spoked asterisk', value: '✳️' },
                { title: 'Eight pointed star', value: '✴️' },
                { title: 'Sparkle', value: '❇️' },
                { title: 'Double exclamation mark', value: '‼️' },
                { title: 'Exclamation question mark', value: '⁉️' },
                { title: 'Question mark', value: '❓️' },
                { title: 'White question mark', value: '❔️' },
                { title: 'White exclamation mark', value: '❕️' },
                { title: 'Exclamation mark', value: '❗️' },
                { title: 'Wavy dash', value: '〰️' },
                { title: 'Copyright', value: '©️' },
                { title: 'Registered', value: '®️' },
                { title: 'Trademark', value: '™️' },
                { title: 'Keycap', value: '#️⃣' },
                { title: 'Keycap 0', value: '0️⃣' },
                { title: 'Keycap 1', value: '1️⃣' },
                { title: 'Keycap 2', value: '2️⃣' },
                { title: 'Keycap 3', value: '3️⃣' },
                { title: 'Keycap 4', value: '4️⃣' },
                { title: 'Keycap 5', value: '5️⃣' },
                { title: 'Keycap 6', value: '6️⃣' },
                { title: 'Keycap 7', value: '7️⃣' },
                { title: 'Keycap 8', value: '8️⃣' },
                { title: 'Keycap 9', value: '9️⃣' },
                { title: 'Keycap 10', value: '🔟' },
                { title: 'Hundred points', value: '💯' },
                { title: 'Input latin uppercase', value: '🔠' },
                { title: 'Input latin lowercase', value: '🔡' },
                { title: 'Input numbers', value: '🔢' },
                { title: 'Input symbols', value: '🔣' },
                { title: 'Input latin letters', value: '🔤' },
                { title: 'A button blood type', value: '🅰' },
                { title: 'Ab button blood type', value: '🆎' },
                { title: 'B button blood type', value: '🅱' },
                { title: 'Cl button', value: '🆑' },
                { title: 'Cool button', value: '🆒' },
                { title: 'Free button', value: '🆓' },
                { title: 'Information', value: 'ℹ️' },
                { title: 'Id button', value: '🆔' },
                { title: 'Circled m', value: 'Ⓜ️' },
                { title: 'New button', value: '🆕' },
                { title: 'Ng button', value: '🆖' },
                { title: 'O button blood type', value: '🅾' },
                { title: 'Ok button', value: '🆗' },
                { title: 'P button', value: '🅿' },
                { title: 'SOS button', value: '🆘' },
                { title: 'Up button', value: '🆙' },
                { title: 'Vs button', value: '🆚' },
                { title: 'Japanese here button', value: '🈁' },
                { title: 'Japanese service charge button', value: '🈂' },
                { title: 'Japanese monthly amount button', value: '🈷' },
                { title: 'Japanese not free of charge button', value: '🈶' },
                { title: 'Japanese reserved button', value: '🈯' },
                { title: 'Japanese bargain button', value: '🉐' },
                { title: 'Japanese discount button', value: '🈹' },
                { title: 'Japanese free of charge button', value: '🈚' },
                { title: 'Japanese prohibited button', value: '🈲' },
                { title: 'Japanese acceptable button', value: '🉑' },
                { title: 'Japanese application button', value: '🈸' },
                { title: 'Japanese passing grade button', value: '🈴' },
                { title: 'Japanese vacancy button', value: '🈳' },
                { title: 'Japanese congratulations button', value: '㊗' },
                { title: 'Japanese secret button', value: '㊙' },
                { title: 'Japanese open for business button', value: '🈺' },
                { title: 'Japanese no vacancy button', value: '🈵' },
                { title: 'Black small square', value: '▪️' },
                { title: 'White small square', value: '▫️' },
                { title: 'White medium square', value: '◻️' },
                { title: 'Black medium square', value: '◼️' },
                { title: 'White medium small square', value: '◽️' },
                { title: 'Black medium small square', value: '◾️' },
                { title: 'Black large square', value: '⬛️' },
                { title: 'White large square', value: '⬜️' },
                { title: 'Large orange diamond', value: '🔶' },
                { title: 'Large blue diamond', value: '🔷' },
                { title: 'Small orange diamond', value: '🔸' },
                { title: 'Small blue diamond', value: '🔹' },
                { title: 'Red triangle pointed up', value: '🔺' },
                { title: 'Red triangle pointed down', value: '🔻' },
                { title: 'Diamond with a dot', value: '💠' },
                { title: 'Radio button', value: '🔘' },
                { title: 'Black square button', value: '🔲' },
                { title: 'White square button', value: '🔳' },
                { title: 'White circle', value: '⚪' },
                { title: 'Black circle', value: '⚫' },
                { title: 'Red circle', value: '🔴' },
                { title: 'Blue circle', value: '🔵' }
            ]
        },
        {
            title: 'Flags',
            value: 'Flags',
            emojis: [
                { title: 'Chequered flag', value: '🏁' },
                { title: 'Triangular flag', value: '🚩' },
                { title: 'Crossed flags', value: '🎌' },
                { title: 'United Arab Emirates', value: '🇦🇪' },
                { title: 'Austria', value: '🇦🇹' },
                { title: 'Australia', value: '🇦🇺' },
                { title: 'Belgium', value: '🇧🇪' },
                { title: 'Brazil', value: '🇧🇷' },
                { title: 'Canada', value: '🇨🇦' },
                { title: 'Switzerland', value: '🇨🇭' },
                { title: 'Chile', value: '🇨🇱' },
                { title: 'China', value: '🇨🇳' },
                { title: 'Colombia', value: '🇨🇴' },
                { title: 'Germany', value: '🇩🇪' },
                { title: 'Denmark', value: '🇩🇰' },
                { title: 'Spain', value: '🇪🇸' },
                { title: 'Finland', value: '🇫🇮' },
                { title: 'France', value: '🇫🇷' },
                { title: 'United Kingdom', value: '🇬🇧' },
                { title: 'Hong Kong Sar China', value: '🇭🇰' },
                { title: 'Indonesia', value: '🇮🇩' },
                { title: 'Ireland', value: '🇮🇪' },
                { title: 'Israel', value: '🇮🇱' },
                { title: 'India', value: '🇮🇳' },
                { title: 'Italy', value: '🇮🇹' },
                { title: 'Japan', value: '🇯🇵' },
                { title: 'South Korea', value: '🇰🇷' },
                { title: 'Macau Sar China', value: '🇲🇴' },
                { title: 'Mexico', value: '🇲🇽' },
                { title: 'Malaysia', value: '🇲🇾' },
                { title: 'Netherlands', value: '🇳🇱' },
                { title: 'Norway', value: '🇳🇴' },
                { title: 'New Zealand', value: '🇳🇿' },
                { title: 'Philippines', value: '🇵🇭' },
                { title: 'Poland', value: '🇵🇱' },
                { title: 'Puerto Rico', value: '🇵🇷' },
                { title: 'Portugal', value: '🇵🇹' },
                { title: 'Russia', value: '🇷🇺' },
                { title: 'Saudi Arabia', value: '🇸🇦' },
                { title: 'Sweden', value: '🇸🇪' },
                { title: 'Singapore', value: '🇸🇬' },
                { title: 'Turkey', value: '🇹🇷' },
                { title: 'United States', value: '🇺🇸' },
                { title: 'Vietnam', value: '🇻🇳' },
                { title: 'South Africa', value: '🇿🇦' }
            ]
        }
    ];
}
