import '@lwc/synthetic-shadow';
import AutoDataType from 'avonni/autoDataType';
import AvatarGroup from 'avonni/avatarGroup';
import BadgeIcon from 'avonni/badgeIcon';
import Calendar from 'avonni/calendar';
import Carousel from 'avonni/carousel';
import ChartBar from 'avonni/chartBar';
import ChartFunnel from 'avonni/chartFunnel';
import ChartHeatmap from 'avonni/chartHeatmap';
import ChartLine from 'avonni/chartLine';
import ChartPie from 'avonni/chartPie';
import ChartTreemap from 'avonni/chartTreemap';
import CheckboxGroup from 'avonni/checkboxGroup';
import ColorGradient from 'avonni/colorGradient';
import ColorPalette from 'avonni/colorPalette';
import ColorPicker from 'avonni/colorPicker';
import Confetti from 'avonni/confetti';
import Image from 'avonni/image';
import InputCounter from 'avonni/inputCounter';
import InputDateRange from 'avonni/inputDateRange';
import InputPen from 'avonni/inputPen';
import InputToggle from 'avonni/inputToggle';
import Kanban from 'avonni/kanban';
import Pagination from 'avonni/pagination';
import ProgressCircle from 'avonni/progressCircle';
import Qrcode from 'avonni/qrcode';
import Range from 'avonni/range';
import Rating from 'avonni/rating';
import Timer from 'avonni/timer';
import VisualPicker from 'avonni/visualPicker';

customElements.define('ac-avonni-auto-data-type', AutoDataType.CustomElementConstructor);
customElements.define('ac-avonni-avatar-group', AvatarGroup.CustomElementConstructor);
customElements.define('ac-avonni-badge-icon', BadgeIcon.CustomElementConstructor);
customElements.define('ac-avonni-calendar', Calendar.CustomElementConstructor);
customElements.define('ac-avonni-carousel', Carousel.CustomElementConstructor);
customElements.define('ac-avonni-chart-bar', ChartBar.CustomElementConstructor);
customElements.define('ac-avonni-chart-funnel', ChartFunnel.CustomElementConstructor);
customElements.define('ac-avonni-chart-heatmap', ChartHeatmap.CustomElementConstructor);
customElements.define('ac-avonni-chart-line', ChartLine.CustomElementConstructor);
customElements.define('ac-avonni-chart-pie', ChartPie.CustomElementConstructor);
customElements.define('ac-avonni-chart-treemap', ChartTreemap.CustomElementConstructor);
customElements.define('ac-avonni-checkbox-group', CheckboxGroup.CustomElementConstructor);
customElements.define('ac-avonni-color-gradient', ColorGradient.CustomElementConstructor);
customElements.define('ac-avonni-color-palette', ColorPalette.CustomElementConstructor);
customElements.define('ac-avonni-color-picker', ColorPicker.CustomElementConstructor);
customElements.define('ac-avonni-confetti', Confetti.CustomElementConstructor);
customElements.define('ac-avonni-image', Image.CustomElementConstructor);
customElements.define('ac-avonni-input-counter', InputCounter.CustomElementConstructor);
customElements.define('ac-avonni-input-date-range', InputDateRange.CustomElementConstructor);
customElements.define('ac-avonni-input-pen', InputPen.CustomElementConstructor);
customElements.define('ac-avonni-input-toggle', InputToggle.CustomElementConstructor);
customElements.define('ac-avonni-kanban', Kanban.CustomElementConstructor);
customElements.define('ac-avonni-pagination', Pagination.CustomElementConstructor);
customElements.define('ac-avonni-progress-circle', ProgressCircle.CustomElementConstructor);
customElements.define('ac-avonni-qrcode', Qrcode.CustomElementConstructor);
customElements.define('ac-avonni-range', Range.CustomElementConstructor);
customElements.define('ac-avonni-rating', Rating.CustomElementConstructor);
customElements.define('ac-avonni-timer', Timer.CustomElementConstructor);
customElements.define('ac-avonni-visual-picker', VisualPicker.CustomElementConstructor);